Manejar errores al mover archivos al repositorio

diff --git a/src/dotfiles b/src/dotfiles
--- a/src/dotfiles
+++ b/src/dotfiles
@@ -10,6 +10,10 @@ add_path(){
 	fi
 	((RECURSION_DEPTH++))
 	for path in "$@"; do
+		if [ -L "$path" ]; then
+            echo "OMITIDO: $path es un enlace simbólico (posiblemente ya en dotsync)"
+            continue
+        fi
 		if ! [ -e "$path" ]; then 
 			echo "ERROR: $path no existe"
 			continue
@@ -19,6 +23,10 @@ add_path(){
 			echo "ERROR: No se pudo añadir $full_path porque no está en $HOME"
 			continue
 		fi
+		if [[ "$full_path" == "$REPO"* ]]; then
+			echo "ERROR: No puedes añadir el propio repositorio dotsync"
+			continue
+    	fi
 		local repo_path="${full_path/$HOME/$REPO}"	# Ruta en el repositorio dotsync
 		local basename="${full_path##*/}"
 		if is_excluded "$basename"; then
@@ -26,9 +34,15 @@ add_path(){
 			continue
 		fi
 		if [ -f "$full_path" ]; then
-			mkdir -p "${repo_path%/*}"
+			if ! mkdir -p "${repo_path%/*}"; then
+				echo "ERROR: No se pudo crear directorio ${repo_path%/*}"
+				continue;
+			fi
 			echo "Moviendo $full_path a $repo_path"
-			mv "$full_path" "$repo_path"
+			if ! mv "$full_path" "$repo_path"; then
+				echo "ERROR: No se pudo mover el archivo"
+				continue;
+			fi
 		elif [ -d "$full_path" ]; then
 			add_path "$full_path"/*		# Llama a esta misma función recursivamente
 		else 
@@ -41,13 +55,13 @@ add_path(){
 		echo "Finalizando sincronización con git y stow"
 		(
 			cd "$REPO"
-			git add .
+			git add . > /dev/null
 			if [ "$#" -eq 1 ]; then
-				git commit -m "AÑADIR: $1" -m "Se han añadido $1 al repositorio dotsync"
+				git commit -m "AÑADIR: $1" -m "Se han añadido $1 al repositorio dotsync" > /dev/null
 			else
-				git commit -m "AÑADIR: Varios archivos" -m "Se han añadido con éxito varios archivos y/o directorios"
+				git commit -m "AÑADIR: Varios archivos" -m "Se han añadido con éxito varios archivos y/o directorios" > /dev/null
 			fi
-			stow .
+			stow . > /dev/null
 		)
 	fi
 	return 0
