BUGFIX: En la comprobación del repositorio
Si no tenías el repositorio creado, no dejaba crearlo porque salía del programa inmediantemente

diff --git a/src/main b/src/main
--- a/src/main
+++ b/src/main
@@ -10,10 +10,6 @@ shopt -s nullglob
 timestamp=$(date +%s)
 
 main(){
-	if ! [ -d "$REPO" ]; then
-		echo -e "ERROR: No existe el repositorio dotsync\nEjecuta <dotsync init> para crearlo" >&2
-		exit 1
-	fi
 	check_deps "${DEPS[@]}" || exit 1
 	git_check_changes || exit 1
 	load_config || exit 1
@@ -23,6 +19,10 @@ main(){
 	fi
 	opt="$1"
 	shift
+	if ! [ -d "$REPO" ] && [[ "$OPT" != "init" ]]; then
+		echo -e "ERROR: No existe el repositorio dotsync\nEjecuta <dotsync init> para crearlo" >&2
+		exit 1
+	fi
 	case "$opt" in
 		"init") 
 			init_dotsync
