Imprimir error de 'comando no encontrado' si no se encuentra el comando

diff --git a/src/main b/src/main
--- a/src/main
+++ b/src/main
@@ -94,6 +94,7 @@ main() {
         print_version
         ;;
     *)
+        echo "ERROR: Commandp $opt no encontrado" >&2
         help
         ;;
     esac
