Sólo comprobar dependencias si el repositorio está creado
Si no está creado, los comandos fallarán

diff --git a/src/main b/src/main
--- a/src/main
+++ b/src/main
@@ -16,13 +16,15 @@ main(){
 	fi
 	opt="$1"
 	shift
-	if ! [ -d "$REPO" ] && [[ "$opt" != "init" ]]; then
-		echo -e "ERROR: No existe el repositorio dotsync\nEjecuta <dotsync init> para crearlo" >&2
-		exit 1
+	if [[ "$opt" != "init" ]]; then
+		if ! [ -d "$REPO" ]; then
+			echo -e "ERROR: No existe el repositorio dotsync\nEjecuta <dotsync init> para crearlo" >&2
+			exit 1
+		fi
+		check_deps "${DEPS[@]}" || exit 1
+		git_check_changes || exit 1
+		load_config || exit 1
 	fi
-	check_deps "${DEPS[@]}" || exit 1
-	git_check_changes || exit 1
-	load_config || exit 1
 	case "$opt" in
 		"init"|"i")
 			init_dotsync
