Omitir conflicto si los archivos importados son igualesx
al importar, si los archivos en conflicto son iguales, se pasa al
siguiente sin molestar al usuario.

diff --git a/src/sync b/src/sync
--- a/src/sync
+++ b/src/sync
@@ -218,49 +218,59 @@ sync_import() {
 
             local file_after_symlink="${file_repo/${REPO}/${HOME}}"
             if [ -e "$file_repo" ]; then
-                echo "$file ya existe en el repositorio"
-                echo "¿Deseas reemplazarlo?"
-                local ans
-                select ans in \
-                    "Sí: Reemplazar archivo existente por archivo descargado" \
-                    "Ver differencias entre archivos" \
-                    "No: Dejar archivo existente como está"; do
-                    if [[ "$ans" == *"dif"* ]]; then
-                        pager "$(diff "$file_repo" "$file")"
-                        continue # Continue no sale de select
-                    fi
-                    [[ -n "$ans" ]] && break
-                done
-                if [[ "$ans" == "S"* ]]; then
-                    if ! rm "$file_repo"; then
-                        echo "Error al eliminar el archivo $file_repo, no se añadirá al repositorio"
+                local file_diff="$(diff "$file_repo" "$file")"
+                if [ -n "$file_diff" ]; then    
+                    echo "$file ya existe en el repositorio"
+                    echo "¿Deseas reemplazarlo?"
+                    local ans
+                    select ans in \
+                        "Sí: Reemplazar archivo existente por archivo descargado" \
+                        "Ver differencias entre archivos" \
+                        "No: Dejar archivo existente como está"; do
+                        if [[ "$ans" == *"dif"* ]]; then
+                            pager "$file_diff"
+                            continue # Continue no sale de select
+                        fi
+                        [[ -n "$ans" ]] && break
+                    done
+                    if [[ "$ans" == "S"* ]]; then
+                        if ! rm "$file_repo"; then
+                            echo "Error al eliminar el archivo $file_repo, no se añadirá al repositorio"
+                            continue
+                        fi
+                    elif [[ "$ans" == "N"* ]]; then
                         continue
                     fi
-                elif [[ "$ans" == "N"* ]]; then
+                else
                     continue
                 fi
             # Comprobar si el archivo podría entrar en conflicto con stow cuando se genere el enlace simbólico en $HOME
             # Esto evita conflictos de stow si $HOME/.config/nvim existe pero no está en el repositorio
             # Comprobar si el archivo NO existe en el repositorio
             elif [ -f "$file_after_symlink" ]; then
-                echo "$file_after_symlink ya existe en el sistema"
-                echo "¿Deseas reemplazarlo por el archivo descargado?"
-                select ans in \
-                    "Sí: Reemplazar archivo existente por archivo descargado" \
-                    "Ver differencias entre archivos" \
-                    "No: Dejar archivo existente como está"; do
-                    if [[ "$ans" == *"dif"* ]]; then
-                        pager "$(diff "$file_real" "$file_after_symlink")"
-                        continue # Continue no sale de select
-                    fi
-                    [[ -n "$ans" ]] && break
-                done
-                if [[ "$ans" == "S"* ]]; then
-                    if ! rm "$file_after_symlink"; then
-                        echo "Error al eliminar el archivo $file_after_symlink, no se añadirá al repositorio"
+                local file_diff="$(diff "$file_real" "$file_after_symlink")"
+                if [ -n "$file_diff" ]; then    
+                    echo "$file_after_symlink ya existe en el sistema"
+                    echo "¿Deseas reemplazarlo por el archivo descargado?"
+                    select ans in \
+                        "Sí: Reemplazar archivo existente por archivo descargado" \
+                        "Ver differencias entre archivos" \
+                        "No: Dejar archivo existente como está"; do
+                        if [[ "$ans" == *"dif"* ]]; then
+                            pager "$file_diff"
+                            continue # Continue no sale de select
+                        fi
+                        [[ -n "$ans" ]] && break
+                    done
+                    if [[ "$ans" == "S"* ]]; then
+                        if ! rm "$file_after_symlink"; then
+                            echo "Error al eliminar el archivo $file_after_symlink, no se añadirá al repositorio"
+                            continue
+                        fi
+                    elif [[ "$ans" == "N"* ]]; then
                         continue
                     fi
-                elif [[ "$ans" == "N"* ]]; then
+                else
                     continue
                 fi
             fi
