BUGFIX: Mensaje de conflicto se mostraba dos veces al importar
Al importar, si un archivo descargado existía en el repositorio,
mostraba un mensaje de conflicto, y si existía en el sistema (fuera de
dotsync) mostraba otro.
Pero si el archivo existe en el repositorio existirá también en el
sistema, por lo que solo es correcto mostrar un mensaje de conflicto.

diff --git a/src/sync b/src/sync
--- a/src/sync
+++ b/src/sync
@@ -216,22 +216,33 @@ sync_import() {
             local dest_dir="${file_repo%/*}"
             mkdir -p "$dest_dir"
 
+            local file_after_symlink="${file_repo/${REPO}/${HOME}}"
             if [ -e "$file_repo" ]; then
                 echo "$file ya existe en el repositorio"
                 echo "¿Deseas reemplazarlo?"
                 local ans
-                select ans in "Sí: Reemplazar archivo existente por archivo descargado" "No: Dejar archivo existente como está"; do
-                    [ -n "$ans" ] && break
+                select ans in \
+                    "Sí: Reemplazar archivo existente por archivo descargado" \
+                    "Ver differencias entre archivos" \
+                    "No: Dejar archivo existente como está"; do
+                    if [[ "$ans" == *"dif"* ]]; then
+                        pager "$(diff "$file_repo" "$file")"
+                        continue # Continue no sale de select
+                    fi
+                    [[ -n "$ans" ]] && break
                 done
-                if [[ "$ans" == "No"* ]]; then
+                if [[ "$ans" == "S"* ]]; then
+                    if ! rm "$file_repo"; then
+                        echo "Error al eliminar el archivo $file_repo, no se añadirá al repositorio"
+                        continue
+                    fi
+                elif [[ "$ans" == "N"* ]]; then
                     continue
                 fi
-            fi
-
             # Comprobar si el archivo podría entrar en conflicto con stow cuando se genere el enlace simbólico en $HOME
             # Esto evita conflictos de stow si $HOME/.config/nvim existe pero no está en el repositorio
-            local file_after_symlink="${file_repo/${REPO}/${HOME}}"
-            if [ -f "$file_after_symlink" ]; then
+            # Comprobar si el archivo NO existe en el repositorio
+            elif [ -f "$file_after_symlink" ]; then
                 echo "$file_after_symlink ya existe en el sistema"
                 echo "¿Deseas reemplazarlo por el archivo descargado?"
                 select ans in \
@@ -246,7 +257,7 @@ sync_import() {
                 done
                 if [[ "$ans" == "S"* ]]; then
                     if ! rm "$file_after_symlink"; then
-                        echo "Error al eliminar el archivo $file_after_symlink, no se añadirá $file_repo al repositorio"
+                        echo "Error al eliminar el archivo $file_after_symlink, no se añadirá al repositorio"
                         continue
                     fi
                 elif [[ "$ans" == "N"* ]]; then
